spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_students?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false



  main:
     allow-bean-definition-overriding: true

server:
  port: 9093




#logging:
 # level:
  #  org:
   #   springframework:
    #    batch:
    #      DEBUG
     #   oxm:
      #    jaxb:
         #   DEBUG
